/* Heirz Holding  service catalogue, drawn from the 2026 print profile */
window.HEIRZ_SERVICES = [
  {
    cat: 'insurance-coffee', catLabel: 'Insurance & Coffee',
    title: 'Insurance Agency Services',
    img: 'assets/services/insurance.jpg',
    teaser: 'Health, property, life, motor and commercial cover, customised to protect what matters to you.',
    full: 'At Heirz Holding, we understand the significance of safeguarding your assets, health and future. Our Insurance Agency Services cover a wide spectrum, including Health insurance, property and casualty insurance, life insurance, vehicle insurance, and commercial insurance. Our experienced professionals work closely with you to customise insurance solutions that provide peace of mind and financial security. Fire, Goods in transit, Bond, Motor, Theft/Burglary and Health are all part of what we offer.',
    highlights: ['Property Insurance', 'Life Insurance', 'Health Insurance', 'Motor Insurance', 'Business Continuity', 'Risk Management'],
  },
  {
    cat: 'insurance-coffee', catLabel: 'Insurance & Coffee',
    title: 'Coffee Trading & Supply',
    img: 'assets/services/coffee.jpg',
    teaser: 'Premium Arabica coffee from Rwanda\u2019s highlands  exported and wholesaled at home and abroad.',
    full: 'HEIRZ Coffee is a premium Arabica coffee sourced from Rwanda\u2019s fertile highlands. Carefully selected and expertly roasted, it delivers a rich aroma, smooth body and authentic taste that reflects Rwanda\u2019s coffee excellence. We export and wholesale premium Rwandan coffee to local and international markets  Premium Arabica whole beans, medium roast, rich aroma, smooth body, balanced taste, proudly a product of Rwanda.',
    rw: 'HEIRZ Coffee ni kawa ya Arabica y\u2019indashyikirwa ikomoka mu misozi y\u2019u Rwanda, itoranywa kandi igakokwa mu buryo bw\u2019umwuga.',
    highlights: ['Whole Beans', 'Medium Roast', 'Export & Wholesale', 'Product of Rwanda'],
  },
  {
    cat: 'agri-trade', catLabel: 'Agriculture & Trade',
    title: 'Agricultural Equipment & Irrigation',
    img: 'assets/services/agriculture.jpg',
    teaser: 'Modern farm equipment and irrigation systems built to raise yield and water efficiency.',
    full: 'We supply modern agricultural equipment and irrigation solutions that help farmers increase productivity, improve crop quality and promote sustainable farming practices. Our products are designed to support efficient water management and modern agricultural development.',
    rw: 'Dutanga ibikoresho by\u2019ubuhinzi bigezweho n\u2019ibisubizo by\u2019uhirira bifasha abahinzi kongera umusaruro no guteza imbere ubuhinzi burambye.',
    highlights: ['Agricultural Equipment', 'Irrigation Systems', 'Water Management', 'Sustainable Agriculture'],
  },
  {
    cat: 'agri-trade', catLabel: 'Agriculture & Trade',
    title: 'Transport & Logistics',
    img: 'assets/services/transport.jpg',
    teaser: 'Safe, timely movement of goods  plus real estate, construction and general trading.',
    full: 'Heirz Holding provides reliable transport and logistics solutions designed to ensure the safe, timely and efficient movement of goods. Our commitment to professionalism and customer satisfaction helps businesses streamline their supply chains and reach their markets with confidence. Alongside logistics, this arm also covers Real Estate, General Trading, Construction and Agro Business.',
    rw: 'Heirz Holding itanga serivisi zizewe zo gutwara no gukwirakwiza ibicuruzwa, hagamijwe umutekano n\u2019igihe.',
    highlights: ['Real Estate', 'General Trading', 'Transport & Logistics', 'Construction', 'Agro Business'],
  },
  {
    cat: 'automotive', catLabel: 'Automotive',
    title: 'Fuel Pumps & Auto Spare Parts',
    img: 'assets/services/fuel-auto-parts.jpg',
    teaser: 'A dependable source for fuel pumps and a wide assortment of auto spare parts.',
    full: 'Heirz Holding serves as your dependable source for reliable fuel pumps and an extensive assortment of auto spare parts to keep your vehicles running smoothly.',
    highlights: ['Fuel Pumps', 'Auto Spare Parts'],
  },
  {
    cat: 'automotive', catLabel: 'Automotive',
    title: 'Spare Parts',
    img: 'assets/services/spare-parts.jpg',
    teaser: 'Genuine automotive, industrial and machinery spare parts, always in stock.',
    full: 'Heirz Holding supplies genuine automotive, industrial and machinery spare parts. We recognise the critical role quality spare parts play in maintaining the efficiency and reliability of your equipment and machines. Our extensive inventory and commitment to authenticity ensure your operations run smoothly. Don\u2019t compromise on the efficiency and productivity of your business  contact us today to explore our extensive inventory of genuine spare parts.',
    highlights: ['Genuine Parts', 'Industrial & Machinery', 'Large Inventory'],
  },
  {
    cat: 'automotive', catLabel: 'Automotive',
    title: 'Tires',
    img: 'assets/services/tires.png',
    teaser: 'Passenger, SUV, truck and heavy-duty tires for vehicles and machinery of every kind.',
    full: 'Heirz Holding Company Limited offers a diverse selection of tires to cater to a wide range of needs and applications. Whether you require tires for your vehicles, industrial machinery or specialised equipment, we have you covered with quality and durability  from passenger cars, SUVs, trucks and commercial vehicles to heavy-duty tires for vehicles and machineries.',
    highlights: ['Passenger & SUV', 'Trucks', 'Industrial & Heavy-duty'],
  },
  {
    cat: 'automotive', catLabel: 'Automotive',
    title: 'Auto-Garage Services',
    img: 'assets/services/auto-garage.jpg',
    teaser: 'Routine maintenance, major repairs and fleet management, done right.',
    full: 'Whether you need routine maintenance, major repairs or fleet management services, Heirz Holding Company Limited is your reliable partner. We deliver efficient, cost-effective and customer-focused auto-garage services to keep your vehicles in top condition.',
    highlights: ['Maintenance', 'Major Repairs', 'Fleet Management'],
  },
  {
    cat: 'automotive', catLabel: 'Automotive',
    title: 'Lubricants and Oil',
    img: 'assets/services/lubricants.jpg',
    teaser: 'High-quality lubricants and oils engineered for precision and optimal performance.',
    full: 'Heirz Holding Company Limited takes pride in offering a comprehensive range of high-quality lubricants and oils to meet the diverse needs of industries and individuals. Our lubricants and oils are engineered for precision, reliability and optimal performance, ensuring the smooth operation of machinery, vehicles and equipment.',
    highlights: ['Industrial Use', 'Vehicles', 'Machinery'],
  },
  {
    cat: 'safety-tools', catLabel: 'Safety & Tools',
    title: 'Safety Gears',
    img: 'assets/services/safety-gears.jpg',
    teaser: 'High-quality PPE  helmets, gloves, protective clothing, boots and more.',
    full: 'Safety is paramount, and our commitment to safety extends to various industries. We supply high-quality Safety Gears and Personal Protective Equipment (PPE) to ensure the well-being of workers  from helmets and gloves to protective clothing, shoes to gum boots, eye to ear protection, and so on. We offer a comprehensive range of safety gears for various industries, ensuring the well-being of your workforce.',
    highlights: ['Helmets & Gloves', 'Protective Clothing', 'Eye & Ear Protection'],
  },
  {
    cat: 'safety-tools', catLabel: 'Safety & Tools',
    title: 'Hand Tools and Machinery',
    img: 'assets/services/hand-tools.jpg',
    teaser: 'Wrenches to welding machines  tools crafted for precision, durability and efficiency.',
    full: 'Heirz Holding Company Limited offers an extensive range of high-quality hand tools and machinery for professionals, businesses and individuals across various industries. Our range includes wrenches, screwdrivers, pliers, hammers, drills, saws, grinders and other electric and cordless tools, concrete mixers, compactors and scaffolding, planers, routers and sanders for woodworking, metalworking tools for shaping, cutting and fabricating metal, plus welding machines, air compressors and hydraulic presses.',
    highlights: ['Hand Tools', 'Power Tools', 'Welding & Compressors'],
  },
  {
    cat: 'energy-security', catLabel: 'Energy & Security',
    title: 'Solar Systems',
    img: 'assets/services/solar.jpg',
    teaser: 'Clean, renewable solar solutions for homes, businesses and communities.',
    full: 'We offer a comprehensive range of solar systems and services to cater to the energy needs of individuals, businesses and communities. Our solar solutions are designed to harness the power of the sun efficiently and provide clean, renewable energy for a brighter and more sustainable future.',
    highlights: ['Residential', 'Commercial', 'Renewable Energy'],
  },
  {
    cat: 'energy-security', catLabel: 'Energy & Security',
    title: 'Security Cameras (CCTV)',
    img: 'assets/services/cctv.png',
    teaser: 'Cutting-edge CCTV systems safeguarding property, assets and loved ones.',
    full: 'Heirz Holding Company Limited is your trusted partner in safeguarding your property, assets and loved ones with our cutting-edge security camera systems, commonly known as Closed-Circuit Television (CCTV). Our CCTV solutions are designed to provide comprehensive surveillance, enhance security and offer peace of mind to individuals, businesses and communities.',
    highlights: ['Surveillance', 'Installation', 'Monitoring'],
  },
  {
    cat: 'energy-security', catLabel: 'Energy & Security',
    title: 'Drones',
    img: 'assets/services/drones.png',
    teaser: 'Unmanned aerial vehicles for aerial photography, surveying and data collection.',
    full: 'We offer a wide range of drone solutions to meet the diverse needs of individuals, businesses and industries. Drones, also known as Unmanned Aerial Vehicles (UAVs), are versatile tools that can be used for various applications, from aerial photography and surveying to surveillance and data collection.',
    highlights: ['Aerial Photography', 'Surveying', 'Data Collection'],
  },
  {
    cat: 'industrial-mining', catLabel: 'Industrial & Mining',
    title: 'Minerals and Fuel / Oil',
    img: 'assets/services/minerals.jpg',
    teaser: 'A trusted supplier of minerals, fuels and oil products across industries.',
    full: 'Heirz Holding Company Limited is a trusted supplier of minerals, fuels and oil products, serving a diverse range of industries and businesses. Our commitment to quality, reliability and timely delivery makes us the go-to source for meeting your mineral and energy needs.',
    highlights: ['Minerals', 'Fuels', 'Timely Delivery'],
  },
  {
    cat: 'industrial-mining', catLabel: 'Industrial & Mining',
    title: 'Crushers',
    img: 'assets/services/crushers.jpg',
    teaser: 'Efficient reduction of raw materials for further processing or transport.',
    full: 'Heirz Holding Company Limited stands as a leading provider of specialised machinery and services for crushing, screening, industrial grinding and mineral processing. Our crushers efficiently reduce the size of raw materials, making them suitable for further processing or transport  helping you extract maximum value from your raw materials.',
    highlights: ['Size Reduction', 'Processing', 'Transport-ready Output'],
  },
  {
    cat: 'industrial-mining', catLabel: 'Industrial & Mining',
    title: 'Screeners',
    img: 'assets/services/screeners.jpg',
    teaser: 'Precision separation of materials by size and specific characteristics.',
    full: 'Our screening equipment separates materials based on size or specific characteristics, ensuring the final product meets precise specifications  a critical step across crushing, mining and industrial processing operations.',
    highlights: ['Material Separation', 'Precision Specs'],
  },
  {
    cat: 'industrial-mining', catLabel: 'Industrial & Mining',
    title: 'Industrial Grinders & Mineral Processors',
    img: 'assets/services/industrialgrinder.png',
    teaser: 'Refining materials to precise particle sizes, and unlocking the full value of minerals.',
    full: 'Our industrial grinders refine materials to achieve desired particle sizes and consistency, crucial for various industrial applications. Our mineral processing services encompass the extraction, separation, beneficiation and refinement of minerals, unlocking their full potential for your projects. We invite you to explore the diverse offerings of Heirz Holding and join us in navigating the complexities of today\u2019s world with confidence and success.',
    highlights: ['Particle Sizing', 'Extraction', 'Beneficiation & Refinement'],
  },
  {
    cat: 'office-health-home', catLabel: 'Office, Health & Home',
    title: 'Office Equipment & Stationery',
    img: 'assets/services/office-stationery.jpg',
    teaser: 'Everything to build a productive, organised workspace  from pens to full setups.',
    full: 'Heirz Holding Company Limited is committed to helping you create a productive and organised office environment. Whether you need basic stationery supplies, cutting-edge office equipment or complete workspace solutions, we have you covered  from premium pens and notebooks that inspire productivity, to essential office supplies that streamline your work environment, curated for professionals, students and creative enthusiasts alike.',
    highlights: ['Stationery', 'Office Equipment', 'Workspace Solutions'],
  },
  {
    cat: 'office-health-home', catLabel: 'Office, Health & Home',
    title: 'Printing, Graphics & Designing',
    img: 'assets/services/paints.jpg',
    teaser: 'A creative partner for print materials, graphics and design solutions.',
    full: 'Heirz Holding Company Limited is your creative partner for all your printing, graphics and designing needs. We offer a wide range of services to help businesses and individuals bring their ideas to life, whether it\u2019s through eye-catching print materials, compelling graphics or innovative design solutions.',
    highlights: ['Print Materials', 'Graphic Design', 'Branding'],
  },
  {
    cat: 'office-health-home', catLabel: 'Office, Health & Home',
    title: 'Medical Equipment & Supplies',
    img: 'assets/services/medical.jpg',
    teaser: 'High-quality medical equipment supporting healthcare delivery and patient care.',
    full: 'Heirz Holding Company Limited is your trusted source for a wide range of high-quality medical equipment and supplies, catering to healthcare institutions, medical professionals and individuals. Our commitment to excellence ensures reliable, innovative medical solutions that support healthcare delivery and patient care  from hospitals and clinics to home healthcare.',
    highlights: ['Hospitals & Clinics', 'Home Healthcare', 'Patient Care'],
  },
  {
    cat: 'office-health-home', catLabel: 'Office, Health & Home',
    title: 'Kitchenware Products',
    img: 'assets/services/kitchenware.png',
    teaser: 'Cookware to kitchen gadgets, built for function, durability and style.',
    full: 'Heirz Holding Company Limited offers a wide array of high-quality kitchenware products for home cooks, professional chefs and culinary enthusiasts. Our kitchenware collection is designed for functionality, durability and style, making meal preparation a pleasure  Cookware, Bakeware, Cutlery, Kitchen Utensils, Food Storage, Dinnerware, Cooking Tools, Kitchen Gadgets and more.',
    highlights: ['Cookware & Bakeware', 'Utensils', 'Food Storage'],
  }
];
